# Generated by Django 3.2.19 on 2023-06-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Active')], default=1),
        ),
    ]
